config/routes.rb
Omrails::Application.routes.draw do
  devise_for :users

  get 'about' => 'pages#about'
  get 'plans' => 'pages#plans'

  root :to => "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about	
  end

  def plans
  end
 	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
	<li><%= link_to "Twitter", "http://www.twitter.com/georgevaldes"%></li>
	<li><%= link_to "Feather & Mint", "http://featherandmint.com" %></li> 
	 <li><%= link_to "George Valdes", "http://georgevaldes.tumblr.com" %></li>
	
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "a catalog", root_path, :class=> "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
		<ul class="nav">
		
		</ul>  

		<ul class="nav pull-right">
			<% if user_signed_in? %>
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
				<li><%= link_to "Logout", destroy_user_session_path, :method=>:delete %></li>
			<% else %>	
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Plans", plans_path %></li>
			<!--	<li><%= link_to "Login", new_user_session_path %></li> -->
			<% end %>
		</ul>  

      </div>
 

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>the design work of George Valdes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


<link rel="stylesheet" href="css/customui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
 <!--[if lte IE 8]>
     <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.ie.css" />
 <![endif]-->
 <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>  

<script>
  $(function() {
    $( "#accordion" ).accordion();
  });
  </script>

</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container">
		<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, :class=> "alert alert-#{name}") %>
            <% end %>
		<%= yield %>

		
	</div>
	<%= render 'layouts/footer' %>
	

</body>
</html>

app/views/pages/about.html.erb
<!--<div class="hero-unit">
		<h1>About</h1>
	</div>-->


	<div>
		<!--<h2>George Valdes</h2>is a designer entrepreneur working on Feather and Mint.
		This is a repository of his work.-->

<div id="accordion">
  <h3>MUST / KNOW</h3>
  <div>
    <div class="input-wrapper">
    	<p style="font-size:12px;">Wifi info:</p>
          <input type="text" class="w_route" autocomplete="off" id="w_route" name="w_route" placeholder="What's your Router's Name?">
          </p>
        </div>
    <div class="input-wrapper">
          <input type="text" class="w_pass" autocomplete="off" id="w_pass" name="w_pass" placeholder="What's the password?">
          </p>
        </div>
    <small>    
    By filling out these form you'll be providing your guests with access to the internet.
    </small>
  </div>
  <h3>MUST / CARE</h3>
  <div>s
  	<p style="font-size:12px;">Wifi info:</p>
          <input type="text" class="w_route" autocomplete="off" id="w_route" name="w_route" placeholder="What's your Router's Name?">
          </p>
    <p>
    Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
    purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
    velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
    suscipit faucibus urna.
    </p>
  </div>
  <h3>MUST / DO</h3>
  <div>
    <p>
    Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
    Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
    ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
    lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
    </p>
    <ul>
      <li>List item one</li>
      <li>List item two</li>
      <li>List item three</li>
    </ul>
  </div>
  <h3>MUST / CHECKOUT</h3>
  <div>
    <p>
    Cras dictum. Pellentesque habitant morbi tristique senectus et netus
    et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
    faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
    mauris vel est.
    </p>
    <p>
    Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
    inceptos himenaeos.
    </p>
  </div>
</div>
	</div>


	<div class="map-container">
     
    </div>


<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="http://d3js.org/d3.geo.tile.v0.min.js"></script>
<script>

var width = 680,
    height = 300,
    prefix = prefixMatch(["webkit", "ms", "Moz", "O"]);

var tile = d3.geo.tile()
    .size([width, height]);

var projection = d3.geo.mercator()
    .scale((1 << 21) / 2 / Math.PI)
    .translate([-width / 2, -height / 2]); // just temporary

var tileProjection = d3.geo.mercator();

var tilePath = d3.geo.path()
    .projection(tileProjection);

var zoom = d3.behavior.zoom()
    .scale(projection.scale() * 2 * Math.PI)
    .scaleExtent([1 << 20, 1 << 23])
    .translate(projection([-73.97844, 40.68556]).map(function(x) { return -x; }))
    .on("zoom", zoomed);

var map = d3.select("div.map-container").append("div")
    .attr("class", "map")
    .style("width", width + "px")
    .style("height", height + "px")
    .call(zoom)
    .on("mousemove", mousemoved);

var layer = map.append("div")
    .attr("class", "layer");

var info = map.append("div")
    .attr("class", "info");

zoomed();

function zoomed() {
  var tiles = tile
      .scale(zoom.scale())
      .translate(zoom.translate())
      ();

  projection
      .scale(zoom.scale() / 2 / Math.PI)
      .translate(zoom.translate());

  var image = layer
      .style(prefix + "transform", matrix3d(tiles.scale, tiles.translate))
    .selectAll(".tile")
      .data(tiles, function(d) { return d; });

  image.exit()
      .each(function(d) { this._xhr.abort(); })
      .remove();

  image.enter().append("svg")
      .attr("class", "tile")
      .style("left", function(d) { return d[0] * 256 + "px"; })
      .style("top", function(d) { return d[1] * 256 + "px"; })
      .each(function(d) {
        var svg = d3.select(this);
        this._xhr = d3.json("http://" + ["a", "b", "c"][(d[0] * 31 + d[1]) % 3] + ".tile.openstreetmap.us/vectiles-highroad/" + d[2] + "/" + d[0] + "/" + d[1] + ".json", function(error, json) {
          var k = Math.pow(2, d[2]) * 256; // size of the world in pixels

          tilePath.projection()
              .translate([k / 2 - d[0] * 256, k / 2 - d[1] * 256]) // [0°,0°] in pixels
              .scale(k / 2 / Math.PI);

          svg.selectAll("path")
              .data(json.features.sort(function(a, b) { return a.properties.sort_key - b.properties.sort_key; }))
            .enter().append("path")
              .attr("class", function(d) { return d.properties.kind; })
              .attr("d", tilePath);
        });
      });


  image.enter().append("svg")
      .attr("class", "tile")
      .style("left", function(d) { return d[0] * 256 + "px"; })
      .style("top", function(d) { return d[1] * 256 + "px"; })
      .each(function(d) {
        var svg = d3.select(this);
        this._xhr = d3.json("http://" + ["a", "b", "c"][(d[0] * 31 + d[1]) % 3] + ".tile.openstreetmap.us/vectiles-skeleton/" + d[2] + "/" + d[0] + "/" + d[1] + ".json", function(error, json) {
          var k = Math.pow(2, d[2]) * 256; // size of the world in pixels

          tilePath.projection()
              .translate([k / 2 - d[0] * 256, k / 2 - d[1] * 256]) // [0°,0°] in pixels
              .scale(k / 2 / Math.PI);

          svg.selectAll("path")
              .data(json.features.sort(function(a, b) { return a.properties.sort_key - b.properties.sort_key; }))
            .enter().append("path")
              .attr("class", function(d) { return d.properties.kind; })
              .attr("d", tilePath);
        });
      });
}

function mousemoved() {
  info.text(formatLocation(projection.invert(d3.mouse(this)), zoom.scale()));
}

function matrix3d(scale, translate) {
  var k = scale / 256, r = scale % 1 ? Number : Math.round;
  return "matrix3d(" + [k, 0, 0, 0, 0, k, 0, 0, 0, 0, k, 0, r(translate[0] * scale), r(translate[1] * scale), 0, 1 ] + ")";
}

function prefixMatch(p) {
  var i = -1, n = p.length, s = document.body.style;
  while (++i < n) if (p[i] + "Transform" in s) return "-" + p[i].toLowerCase() + "-";
  return "";
}

function formatLocation(p, k) {
  var format = d3.format("." + Math.floor(Math.log(k) / 2 - 2) + "f");
  return (p[1] < 0 ? format(-p[1]) + "°S" : format(p[1]) + "°N") + " "
       + (p[0] < 0 ? format(-p[0]) + "°W" : format(p[0]) + "°E");
}

</script>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>Prepare to get Feathered</h1>
	<p>
		Welcome to the exclusive sign in page of Feather &amp; Mint.
		Please fill out your profile below. </p>
	<div>	
	<li>Wifi</li>
	<li>Amenities</li>
	<li>Recommend</li>
	<li>Checkout</li>	
	</div>


<% else %>	


    
  	<div class="hero-unit">
		<h1>Spatial Futures</h1>
		<!--<p>
			<%= link_to "Sign Up Now!", new_user_registration_path, :class => "btn btn-large btn-primary" %>
		</p>-->
	</div>

 <div class="container">
 	<div class="row">
 		<div class="middle">
 		<h6>~ Interests ~
 		</h6>
 		<br>
 		<div class="span3">
 			<p> 
 			<h4> Computation
 			</h4>
 			<p>
 			I'm interested in the merger between computation and other disciplines.
 			</p>
 			</p>
 		</div>	
 		<div class="span3">
 			<p> 
 			<h4> Entrepreneurship
 			</h4>
 			<p>How can designers leverage their skillsets to develop business models that work?
 			</p>
 			</p>
 		</div>
 			<div class="span3">
 			<p> 
 			<h4> Design Thinking
 			</h4>
 			<p>Design thinking is strategic thinking at its best.
 			</p>
 			</p>
 		</div>
 			<div class="span3">
 			<p> 
 			<h4> Neuro-Computation
 			</h4>
 			<p>The complexity of future thinking is embodied here.
 			</p>
 			</p>
 		</div>

 		</div>
 	</div>
</div>


<% end %>

app/views/pages/plans.html.erb
<h1> Pricing Plan </h1>

<p>Feather & Mint's Pricing Plan is bar none.</p>